name: Build and Deploy
on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

env:
  PEM: ${{ secrets.PEM }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build_android:
    name: Android Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: echo -e "storePassword=${{ secrets.PWD }}\nkeyPassword=${{ secrets.PWD }}\nkeyAlias=upload\nstoreFile=../../upload-keystore.jks" > android/key.properties
      - run: dart gen_secrets.dart

      - run: flutter build apk

      - run: mv build/app/outputs/flutter-apk/app-release.apk inter_knot_android.apk

      - uses: actions/upload-artifact@v4
        with:
          name: inter_knot_apk
          path: inter_knot_android.apk

  build_iOS:
    name: iOS Client
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: dart gen_secrets.dart

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload

      - run: mv build/ios/iphoneos/Runner.app Payload/inter_knot_ios.app

      - run: zip -r9 inter_knot_ios.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: inter_knot_ios
          path: inter_knot_ios.ipa

  release:
    name: Release
    needs:
      - build_android
      - build_iOS
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: inter_knot_apk
          path: inter_knot_apk

      - uses: actions/download-artifact@v4
        with:
          name: inter_knot_ios
          path: inter_knot_ios

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-content.md
          files: |
            inter_knot_apk/inter_knot_android.apk
            inter_knot_ios/inter_knot_ios.ipa
